name: CI

on:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - tagtuner-D1-custom1
          - tagtuner-atom-grove-ble
          - tagtuner-for-tagreader
        esphome-version:
          - stable
          - beta
          # - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
