name: Publish Firmware

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the firmware to build'
        required: true
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: ./.github/workflows/build.yaml
    with:
      #### Modify below here to match your project ####
      files: |
        tagtuner-D1-custom1.factory.yaml
        tagtuner-on-ha-voice-pe.factory.yaml
        tagtuner-atom-grove-ble.factory.yaml
        tagtuner-for-tagreader.factory.yaml
      esphome-version: stable
      combined-name: tagtuner-firmware
      #### Modify above here to match your project ####

      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && inputs.version) || '' }}

  upload-to-release:
    name: Upload to Release
    uses: ./.github/workflows/upload-to-gh-release.yml
    needs:
      - build-firmware
    with:
      version: ${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && inputs.version) || '' }}
