packages:
  core: github://luka6000/TagTuner/tagtuner-for-tagreader.yaml@main

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  project:
    name: LukaGra.TagTuner-8266
    version: dev

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://luka6000/TagTuner/tagtuner-for-tagreader.yaml@main
  import_full_config: true

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
  next_url: https://luka6000.github.io/TagTuner/

wifi:
  ap: !remove
captive_portal: !remove

button:
  - id: !remove btn_erase_tag
  - id: !remove btn_cancel_writing
script:
  - id: !remove action_event
