# These substitutions allow the end user to override certain values
substitutions:
  name: "tagtuner-atom"
  friendly_name: "TagTuner"

packages:
  # Include all of the core configuration
  # core: !include tagtuner-atom-grove-ble.yaml
  core: 
    url: https://github.com/luka6000/TagTuner
    files: tagtuner-atom-grove-ble.yaml
    ref: main
    refresh: 0d

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  project:
    name: LukaGra.TagTuner-Atom
    version: dev

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://luka6000/TagTuner/tagtuner-atom-grove-ble.yaml@main
  import_full_config: true

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
  next_url: https://luka6000.github.io/TagTuner/

esp32_ble:
  name: tagtuner
esp32_improv:
  authorizer: toggle
