# These substitutions allow the end user to override certain values
substitutions:
  name: tagtuner-on-ha-voice
  friendly_name: TagTuner on HA Voice

packages:
  va_connected_wait_for_ble:
    voice_assistant:
      on_client_connected:
        - wait_until:
            not: ble.enabled
        - delay: 2s
    wifi:
      on_disconnect:
        - ble.enable:
  # Include all of the core configuration
  # core: !include tagtuner-on-ha-voice-pe.yaml
  core: 
    url: https://github.com/luka6000/TagTuner
    files: tagtuner-on-ha-voice-pe.yaml
    ref: main
    refresh: 0d

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  project:
    name: LukaGra.TagTuner-on-Home-Assistant-Voice-PE
    version: dev

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://luka6000/TagTuner/tagtuner-on-ha-voice-pe.yaml@main
  import_full_config: true

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
    - script.execute: control_leds

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
  next_url: https://luka6000.github.io/TagTuner/

esp32_ble:
  name: tagtuner
esp32_improv:
  authorizer: center_button
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
